name: pages-visualizations

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'data.yml'
      - 'visualize_data.py'
      - '.github/workflows/pages.yml'
  schedule:
    - cron: '15 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install visualization dependencies
        run: |
          pip install pandas pyyaml matplotlib seaborn numpy scipy
      - name: Ensure data present
        run: |
          python - <<'PY'
          import os, sys
          assert os.path.exists('data.yml'), 'data.yml not found'
          PY
      - name: Generate visualizations
        run: |
          python visualize_data.py
      - name: Build static site
        run: |
          mkdir -p public
          cp -v *.png public/ || true
          cat > public/index.html <<'HTML'
          <!doctype html>
          <html lang="en">
          <meta charset="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>Economic Visualizations</title>
          <style>
            body { font-family: system-ui, sans-serif; margin: 2rem; }
            img { max-width: 100%; height: auto; border: 1px solid #ddd; margin: 1.5rem 0; }
            h1 { margin-bottom: 0.5rem; }
            .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 1rem; }
            .card { padding: 0.5rem; border: 1px solid #eee; border-radius: 8px; background: #fafafa; }
          </style>
          <body>
            <h1>Economic Visualizations</h1>
            <p>Generated by visualize_data.py from data.yml.</p>
            <div class="grid">
              <!-- IMAGE_CARDS -->
            </div>
            <script>
              const files = [
                'economic_indicators_overview.png',
                'correlation_analysis.png',
                'economic_relationships.png',
                'performance_dashboard.png',
                'volatility_analysis.png',
                'm2_area.png',
                'asset_cumulative_analysis.png',
                'economic_regime_analysis.png',
                'economic_ultrathink_dashboard.png',
                'economic_structure_viz.png',
                'stock_flow_framework.png'
              ];
              const grid = document.querySelector('.grid');
              files.forEach(f => {
                const img = document.createElement('img');
                img.src = f; img.alt = f;
                const card = document.createElement('div');
                card.className = 'card';
                const h = document.createElement('h3');
                h.textContent = f.replace(/_/g,' ').replace(/\.png$/,'');
                card.appendChild(h);
                card.appendChild(img);
                grid.appendChild(card);
              });
            </script>
          </body>
          </html>
          HTML
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
