name: update-data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pandas yfinance pyyaml matplotlib requests
      - name: Run update script
        env:
          MPLBACKEND: Agg
        run: python update_data.py
      - name: Upload plot artifact
        uses: actions/upload-artifact@v4
        if: ${{ hashFiles('m2_area.png') != '' }}
        with:
          name: m2-area-plot
          path: m2_area.png
      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.yml
          git commit -m 'Update data' || echo 'No changes to commit'
          git push
